services:
  backend-challenge-02-auth:
    build: .
    ports:
      - 80:80
    env_file:
      - .env
    depends_on:
      backend-challenge-02-auth-db:
        condition: service_healthy

  backend-challenge-02-auth-db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres_data:
